version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - dependabot
    ignore:
      - dependency-name: 'eslint'
        versions: ['9.x']
