language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: webmaster-private@kth.se
  api_key:
    secure: JSBpSOlN+Lr4VCcReGC6jdTC5E6a9svx12hYgMjzlCmvwcHAq3nw/BX2vuLTDPhbBQLNs1rHNSctidmLYr7Vpoj/Wnbl4LL6ZNmSEQNVZIvfr8xPJZxXEgfCsXJuPcfZX73hyKGCQJfa1zUZ5oQvvmhWysgMGYIPELsuvXy6T1qb4jVKMxcv3r7E7VGfhusKVhElLk3aXQ1A+xzcsDyDUKFPhl4+hOFJuKRXfHefmcqLczjh0bXSJDhxZcIdLZi1uZMux/JMVC3Q/wsnLu6LkeMAh2kx7e3d2mSEO3H3890P+umNAGURBvJa7F56NOBNUnvWduh9JVMBepBxx/k5YJ8iwnET9rDWIGwiOS6zhoYnjkImhzD2MD6fw4oZnHwwlFccGD0bDT8Oz9K+ljbL65ljzYQyke2id5pGWVHDFd//uufZWtutAejnYrnq3im2Fh3Y27BM6yI+xjMs6NFvFJRM9nafC91Auh3nSS8LnI7JABNQU6ZcrV9vIBzI3QeSwvdvt6WRC7xNuV51WMRCyEpcsf4qXQeX6hQboWaNknR4lJVasQcD+mMTQa2ZInKTXX+iAQvYhb5g4w/xYd5X3Qg4W7QRf0vBNrxD5hgq8ki0pVPeXkVKW4QagjNNWDVxJ6jQ/YqXCesfL9pFcnElMzPdViHHg5mfL4J/dZtlLRw=
  on:
    tags: true
    repo: KTH/kth-node-redis
notifications:
  slack:
    secure: YzRdKk2qqb3CtJmy9Eb+gL2a3SEn5w7SOunlzIXzbLm7b+/T0et8RPvqip7l48XnqBmGSipkbDMljMAiwwcLdm/mPNDTOPxzr+Ypyb+lZwHy5emGlWtcCLGQOMvsEOVRol6Wy/uQQdwuKrl+O4AiymoBFdZnZl0ETkbH/+wj8oeeP5tHAgd+tpBMtQOTMHzbxTorxQ0NQKjMCX9B+jdn/T/EuAxsjjFdlRl4Q3UGAfd8bcKTxNayxKq4ZIApq/VMUd0KXTB7HCZkvKRk9x4+aCdfZO5C1I66f0DZExPdJ13GiHfTNlIoKyWSj3Ky+XcYei9CxvDxoIYZyBr1q9ovsZRJi6bBPh4FJdNM6hHfMVB9+dwxt/FevFVwJULFQxNHwUr/dtfOwvHXs0GM1Bunjz1sj9HA2315cUFcgZoZRu4UMBqjxgAmkPWCDP6L718cWeIfJZB/lwvoK62QEvvW6ygPGyLpEe3dZRKjI1JjwakVfhIIr6dLF3oM2Wxoi9Ilm+yQ5h6KaW/KkypPCKIALgKY+rcKKthZhk6AW1qnC6amREbo5QeggAgLsIEanEb7spX9tFRSyxJbtf8EDm3SnUoFwGum0RyphuyaF6J4Cl5GKh42yBw70arhFLAp3xHXJSeAPWtaaWdIidJVmyPkg+yeB3OqrdUkcNbHfbhb+J8=
