trigger:
  branches:
    include:
      - main
pr:
  - main

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    stages:
      - stage: build_test
        displayName: Build and test

        jobs:
          - job: unit_test
            displayName: Unit test
            steps:
              - template: /templates/test/npm.yml@stratus-templates
                parameters:
                  nodeVersion: 18
